import { createContext } from 'svelte';

/**
 * Note: Still used by components generated by old versions of Framer
 *
 * @deprecated
 */
export const DeprecatedLayoutGroupContext = createContext<string | null>();
